# Generated by Django 5.2.3 on 2025-06-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-post_id']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='requires_login',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
    ]
