# Generated by Django 5.2.3 on 2025-06-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_blogpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            field=models.IntegerField(default=20),
        ),
    ]
